<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plans_service.proto

namespace Plansservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plansservice.Plan</code>
 */
class Plan extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ID = 1;</code>
     */
    protected $ID = '';
    /**
     * Generated from protobuf field <code>string customerUUID = 2;</code>
     */
    protected $customerUUID = '';
    /**
     * Generated from protobuf field <code>string sku = 3;</code>
     */
    protected $sku = '';
    /**
     * Generated from protobuf field <code>string createdAt = 4;</code>
     */
    protected $createdAt = '';
    /**
     * Generated from protobuf field <code>string updatedAt = 5;</code>
     */
    protected $updatedAt = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ID
     *     @type string $customerUUID
     *     @type string $sku
     *     @type string $createdAt
     *     @type string $updatedAt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PlansService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ID = 1;</code>
     * @return string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>string ID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customerUUID = 2;</code>
     * @return string
     */
    public function getCustomerUUID()
    {
        return $this->customerUUID;
    }

    /**
     * Generated from protobuf field <code>string customerUUID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerUUID($var)
    {
        GPBUtil::checkString($var, True);
        $this->customerUUID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sku = 3;</code>
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * Generated from protobuf field <code>string sku = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSku($var)
    {
        GPBUtil::checkString($var, True);
        $this->sku = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string createdAt = 4;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Generated from protobuf field <code>string createdAt = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->createdAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updatedAt = 5;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Generated from protobuf field <code>string updatedAt = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updatedAt = $var;

        return $this;
    }

}

